# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw/hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw || ORIG_REF_NAME==hw} -quiet] -quiet

# IP: bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_processing_system7_0_0 || ORIG_REF_NAME==hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_axi_gpio_0_0 || ORIG_REF_NAME==hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_xbar_0/hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_xbar_0 || ORIG_REF_NAME==hw_xbar_0} -quiet] -quiet

# IP: bd/hw/ip/hw_ps7_0_axi_periph_0/hw_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rst_ps7_0_50M_0/hw_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_axi_gpio_1_0 || ORIG_REF_NAME==hw_axi_gpio_1_0} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_0/hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_0 || ORIG_REF_NAME==hw_auto_pc_0} -quiet] -quiet

# XDC: /thayerfs/home/f003xh9/workspace/module1/module1.gen/sources_1/bd/hw/hw_ooc.xdc
